name: Wampproto CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: make setup

      - name: Run lint
        run: make check-lint

      - name: build wampproto-cli
        run: make build-wampproto

      - name: Run tests
        run: make test

      - name: Build project
        run: make build
